const productsList = [
  {
    image: "/images/products/shavette.jpg",
    title: "Shavette en Plastique",
    note: "4,2",
    price: "23,00",
    madeInFrance: false,
    vegan: false,
    avis: 3,
  },
  {
    image: "/images/products/setRasage.jpg",
    title: "Set Rasage : Support, Blaireau et Rasoir",
    note: "4,8",
    price: "185,00",
    madeInFrance: false,
    vegan: false,
    avis: 8,
  },
  {
    image: "/images/products/brosse.jpg",
    title: "Brosse pour Barbe",
    note: "4",
    price: "24,90",
    madeInFrance: false,
    vegan: false,
    avis: 1,
  },
  {
    image: "/images/products/huile1.jpg",
    title: "Huile pour Barbe",
    note: "5",
    price: "39,90",
    madeInFrance: false,
    vegan: true,
    avis: 5,
  },
  {
    image: "/images/products/huile2.jpg",
    title: "Huile pour Barbe",
    note: "4,5",
    price: "48,50",
    madeInFrance: true,
    vegan: true,
    avis: 2,
  },
  {
    image: "/images/products/cire1.jpg",
    title: "Cire pour Cheveux",
    note: "4,5",
    price: "25,10",
    madeInFrance: false,
    vegan: false,
    avis: 4,
  },
  {
    image: "/images/products/cire2.jpg",
    title: "Cire pour Cheveux",
    note: "5",
    price: "22,00",
    madeInFrance: false,
    vegan: true,
    avis: 2,
  },
  {
    image: "/images/products/creme1.jpg",
    title: "Creme Hydratante et Tonifiante",
    note: "5",
    price: "22,00",
    madeInFrance: true,
    vegan: true,
    avis: 3,
  },
  {
    image: "/images/products/creme2.jpg",
    title: "Masque Nourrissante et Tonifiant",
    note: null,
    price: "25,00",
    madeInFrance: false,
    vegan: true,
    avis: 0,
  },
];

export default productsList;
